"use client";

import Link from "next/link";
import { OperationPanel } from "@/components/jejak/operation-panel";
import { PageHeading, StateBanner, StatusBadge } from "@/components/seller/seller-ui";
import { formatMoney, moneyPercent, subtractMoney } from "@/lib/jejak/money";
import { useJejak } from "@/lib/jejak/provider";

function SellerState({ children }: { children?: React.ReactNode }) {
  const { context, workspace, loading, error, refresh } = useJejak();
  if (loading) return <div className="seller-page"><div className="workspace-skeleton" aria-label="Loading claim workspace"><span /><span /><span /></div></div>;
  if (error && !workspace) return <div className="seller-page"><StateBanner tone="risk" title={error.title}>{error.detail}</StateBanner><button className="button button-secondary" type="button" onClick={refresh}>Try again</button></div>;
  if (!context) return <div className="seller-page"><StateBanner tone="neutral" title="Choose a demo scenario">Use the persistent demo controls above to reset a happy or adverse workspace.</StateBanner></div>;
  return children;
}

export function SellerDashboard() {
  const { workspace } = useJejak();
  return <SellerState>{workspace && <div className="seller-dashboard">
    <header className="dashboard-header"><div><h1>Dashboard</h1><p>{workspace.claim.marketplace} · checkpoint {workspace.checkpoint}</p></div><StatusBadge tone={workspace.claim.state.includes("LOSS") || workspace.claim.state === "SHORTFALL" ? "risk" : "success"}>{workspace.claim.state.replaceAll("_", " ")}</StatusBadge></header>
    <div className="dashboard-workspace"><div className="dashboard-primary">
      <section className={`dashboard-welcome ${workspace.claim.state === "SHORTFALL" ? "welcome-risk" : ""}`}><div className="welcome-copy"><span>Server-authoritative claim</span><h2>Welcome back, {workspace.claim.sellerName.split(" ")[0]}.</h2><p>{workspace.claim.reasonCodes.map((reason) => reason.replaceAll("_", " ").toLowerCase()).join(" · ")}</p><Link className="dashboard-cta" href={workspace.latestOffer?.status === "ACTIVE" ? `/seller/offers/${workspace.latestOffer.id}` : `/seller/claims/${workspace.claim.id}`}>{workspace.latestOffer?.status === "ACTIVE" ? "Review offer" : "Review claim"}</Link></div><div className="welcome-profile" aria-hidden="true"><span>{workspace.claim.sellerName.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><small>Seller</small></div></section>
      <section className="dashboard-metrics" aria-label="Seller financing summary"><article><span>Unsettled earnings</span><strong>{formatMoney(workspace.claim.gross)}</strong><small>Marketplace gross</small></article><article><span>Eligible value</span><strong>{formatMoney(workspace.claim.esv)}</strong><small>Risk-adjusted snapshot</small></article><article><span>Approved principal</span><strong>{formatMoney(workspace.claim.principal)}</strong><small>{workspace.claim.principal.currency} sandbox asset</small></article><article><span>Expected residual</span><strong>{workspace.latestOffer ? formatMoney(workspace.latestOffer.residual) : "Pending offer"}</strong><small>After obligation</small></article></section>
      <section className="funding-overview"><div className="dashboard-section-heading"><div><h2>Funding position</h2><p>Amounts retain their canonical scale and asset.</p></div><strong>{formatMoney(workspace.claim.esv)}</strong></div><div className="funding-lines"><div className="funding-line"><div><span>Approved principal</span><strong>{formatMoney(workspace.claim.principal)}</strong></div><div className="funding-track"><span className="funding-fill fill-advance" style={{ width: moneyPercent(workspace.claim.principal, workspace.claim.obligation) }} /></div></div><div className="funding-line"><div><span>Obligation</span><strong>{formatMoney(workspace.claim.obligation)}</strong></div><div className="funding-track"><span className="funding-fill fill-fee" style={{ width: "100%" }} /></div></div></div></section>
    </div><aside className="dashboard-activity"><div className="activity-heading"><h2>Claim activity</h2><Link href={`/seller/claims/${workspace.claim.id}`}>View claim</Link></div>{workspace.timeline.slice(0, 5).map((event) => <div className="activity-item" key={event.id}><span className={`activity-dot ${event.state === "SHORTFALL" || event.state === "CLOSED_WITH_LOSS" ? "dot-risk" : ""}`} /><div><strong>{event.label}</strong><small>{new Date(event.occurredAt).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" })}</small></div></div>)}<div className="activity-footnote"><strong>Sandbox simulation</strong><p>No production marketplace, bank account, or Stellar wallet is connected.</p></div></aside></div>
  </div>}</SellerState>;
}

export function SellerOffer() {
  const { workspace } = useJejak();
  return <SellerState>{workspace && <div className="seller-page narrow-page"><PageHeading title="Review your offer" description="Confirm the server terms hash, amount, fee, and obligation." action={<StatusBadge tone={workspace.latestOffer?.status === "ACTIVE" ? "success" : "warning"}>{workspace.latestOffer?.status ?? "NOT READY"}</StatusBadge>} />{workspace.latestOffer ? <section className="offer-sheet"><div className="offer-amount"><span>Funds you receive</span><strong>{formatMoney(workspace.latestOffer.principal)}</strong><p>Sandbox JUSD moves only after issuer and facility authorization.</p></div><dl className="offer-terms"><div><dt>Gross earnings</dt><dd>{formatMoney(workspace.latestOffer.gross)}</dd></div><div><dt>Eligible settlement value</dt><dd>{formatMoney(workspace.latestOffer.esv)}</dd></div><div><dt>Advance factor</dt><dd>{workspace.latestOffer.advanceRateBps / 100}%</dd></div><div><dt>Financing fee</dt><dd>{formatMoney(workspace.latestOffer.fee)}</dd></div><div className="term-total"><dt>Total obligation</dt><dd>{formatMoney(workspace.latestOffer.obligation)}</dd></div><div><dt>Estimated seller residual</dt><dd>{formatMoney(workspace.latestOffer.residual)}</dd></div></dl><div className="terms-note"><div><strong>Exact terms hash</strong><p><code>{workspace.latestOffer.termsHash}</code></p></div><div><strong>Version / expiry</strong><p>v{workspace.latestOffer.version} · {new Date(workspace.latestOffer.expiresAt).toLocaleString("en-GB")}</p></div></div>{workspace.claim.allowedActions.includes("ACCEPT_OFFER") ? <OperationPanel action="ACCEPT_OFFER" /> : <StateBanner tone="neutral" title="No seller confirmation required">The authoritative offer is {workspace.latestOffer.status.toLowerCase()}.</StateBanner>}</section> : <StateBanner tone="warning" title="Offer is not ready">The originator must create an offer before the seller can confirm financial terms.</StateBanner>}</div>}</SellerState>;
}

export function SellerClaim() {
  const { workspace } = useJejak();
  return <SellerState>{workspace && <div className="seller-page"><PageHeading title="Claim journey" description={`${workspace.claim.displayId} · ${workspace.claim.marketplace}`} action={<StatusBadge tone={workspace.claim.state === "CLOSED_WITH_LOSS" || workspace.claim.state === "SHORTFALL" ? "risk" : "success"}>{workspace.claim.state.replaceAll("_", " ")}</StatusBadge>} />{workspace.claim.state === "CLOSED" && <StateBanner tone="success" title="Claim closed">The obligation reconciled and the unused settlement was returned.</StateBanner>}{workspace.claim.state === "CLOSED_WITH_LOSS" && <StateBanner tone="risk" title="Claim closed with a loss">First loss was consumed before the recorded senior final loss. No seller wallet action is required.</StateBanner>}<section className="claim-layout"><div className="seller-timeline-panel"><div className="section-title-row"><div><h2>Claim activity</h2><p>Every item comes from the current workspace checkpoint.</p></div></div><ol className="timeline">{workspace.timeline.map((event, index) => <li className={event.state === "SHORTFALL" || event.state === "CLOSED_WITH_LOSS" ? "timeline-risk" : ""} key={event.id}><div className="timeline-marker" aria-hidden="true">{index + 1}</div><div className="timeline-copy"><div className="timeline-title"><h3>{event.label}</h3><StatusBadge tone={event.state.includes("LOSS") || event.state === "SHORTFALL" ? "risk" : "neutral"}>{event.state}</StatusBadge></div><p>{event.detail}</p><div className="timeline-meta"><span>{new Date(event.occurredAt).toLocaleString("en-GB")}</span><span>{event.actor}</span></div>{event.transactionHash && <a className="transaction-id" href={workspace.stellarReferences.find((ref) => ref.transactionHash === event.transactionHash)?.explorerUrl} target="_blank" rel="noopener noreferrer">TX {event.transactionHash.slice(0, 10)}…</a>}</div></li>)}</ol></div><aside className="claim-summary"><h2>Summary</h2><dl><div><dt>Approved principal</dt><dd>{formatMoney(workspace.claim.principal)}</dd></div><div><dt>Total obligation</dt><dd>{formatMoney(workspace.claim.obligation)}</dd></div><div><dt>Obligation less principal</dt><dd>{formatMoney(subtractMoney(workspace.claim.obligation, workspace.claim.principal))}</dd></div><div><dt>JCC status</dt><dd>{workspace.latestAttestation?.status ?? "Pending"} · Sandbox</dd></div></dl><p className="plain-note">Stellar references are supporting evidence. Sellers never handle seeds or contract calls.</p></aside></section></div>}</SellerState>;
}
