import { AppShell, CaseTable, DataFreshness, Metric, MoneyValue, StatusBadge } from "../components";
import { cases, finalLoss, ResolutionCase, ResolutionStatus } from "../data";

const statusOrder: ResolutionStatus[] = ["OPEN", "IN_REVIEW", "RECOVERED", "CLOSED"];
const priorityOrder: ResolutionCase["priority"][] = ["High", "Medium", "Low"];

export default function ResolutionPortfolioPage() {
  const totals = cases.reduce((acc, item) => ({ obligation: acc.obligation + item.obligation, settlement: acc.settlement + item.realizedSettlement, shortfall: acc.shortfall + item.shortfall, firstLoss: acc.firstLoss + item.firstLossConsumed, recovered: acc.recovered + item.recovered, finalLoss: acc.finalLoss + finalLoss(item) }), { obligation: 0, settlement: 0, shortfall: 0, firstLoss: 0, recovered: 0, finalLoss: 0 });
  const byStatus = statusOrder.map((status) => ({ status, count: cases.filter((item) => item.status === status).length }));
  const byPriority = priorityOrder.map((priority) => ({ priority, count: cases.filter((item) => item.priority === priority).length }));
  return <AppShell><div className="page-header"><div><span className="section-kicker">Resolver workspace</span><h1>Resolution portfolio</h1><p>A rollup of every case in the resolution book — obligation, settlement, and loss allocation across the sandbox.</p></div><DataFreshness>Synced from {cases.length} active cases</DataFreshness></div><div className="metrics"><Metric label="Total obligation" value={<MoneyValue amount={totals.obligation} />} /><Metric label="Realized settlement" value={<MoneyValue amount={totals.settlement} />} /><Metric label="Shortfall" value={<MoneyValue amount={totals.shortfall} negative />} tone="metric-risk" /><Metric label="First-loss consumed" value={<MoneyValue amount={totals.firstLoss} />} /><Metric label="Recovered" value={<MoneyValue amount={totals.recovered} />} tone="metric-success" /><Metric label="Final loss" value={<MoneyValue amount={totals.finalLoss} negative={totals.finalLoss > 0} />} tone={totals.finalLoss > 0 ? "metric-risk" : "metric-success"} /></div><div className="section-band panel-grid"><section className="panel"><div className="panel-heading"><div><span className="section-kicker">Breakdown</span><h2>Status breakdown</h2></div></div>{byStatus.map((row) => <div className="recovery-row" key={row.status}><div><StatusBadge status={row.status} /></div><strong>{row.count}</strong></div>)}</section><section className="panel"><div className="panel-heading"><div><span className="section-kicker">Breakdown</span><h2>By priority</h2></div></div>{byPriority.map((row) => <div className="recovery-row" key={row.priority}><div><strong>{row.priority}</strong></div><strong>{row.count}</strong></div>)}</section></div><div className="list-heading"><div><h2>All cases <span className="count">{cases.length}</span></h2><p>Every case currently tracked in the resolution book.</p></div><span className="sandbox-badge">LOCAL FIXTURE</span></div><CaseTable items={cases} /></AppShell>;
}
