import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { compileFromFile } from "json-schema-to-typescript";

import { loadSchemas, packageRoot } from "./schema-registry.mjs";

const outputRoot = path.join(packageRoot, "src", "generated");
const bannerComment = `/*\n * AUTO-GENERATED FROM packages/domain/schemas.\n * DO NOT EDIT THIS FILE DIRECTLY.\n */`;

await rm(outputRoot, { force: true, recursive: true });
await mkdir(outputRoot, { recursive: true });

const exports = [];
for (const { absolutePath, relativePath, schema } of loadSchemas()) {
  const outputRelativePath = relativePath.replace(/\.schema\.json$/, ".ts");
  const outputPath = path.join(outputRoot, outputRelativePath);
  await mkdir(path.dirname(outputPath), { recursive: true });

  const typescript = await compileFromFile(absolutePath, {
    bannerComment,
    enableConstEnums: false,
    format: true,
    unreachableDefinitions: false,
  });
  await writeFile(outputPath, typescript, "utf8");
  if (typeof schema.title !== "string" || schema.title.length === 0) {
    throw new Error(`Schema ${relativePath} is missing a non-empty title.`);
  }
  exports.push(
    `export type { ${schema.title} } from "./${outputRelativePath.replace(/\.ts$/, ".js")}";`,
  );
}

await writeFile(
  path.join(outputRoot, "index.ts"),
  `${bannerComment}\n${exports.sort().join("\n")}\n`,
  "utf8",
);

process.stdout.write(`Generated ${exports.length} TypeScript schema modules.\n`);
